version: '3.8'
services:
# ************** selenium grid **************
  selenium-grid:
    image: seleniarm/standalone-chromium:latest
    container_name: sele_ac
    ports:
      - "4450:4444"
    environment:
      SE_NODE_MAX_SESSIONS: 10
      SE_NODE_OVERRIDE_MAX_SESSIONS: "true"
      SE_NODE_SESSION_TIMEOUT: 1000
      PYTHONUNBUFFERED: 1
    shm_size: 4g
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - app-network-domain-fe1
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G

# ************** App **************
  app:
    build: .
    container_name: domain-ac
    depends_on:
      - selenium-grid
    environment:
      SELENIUM_ADDRESS: "http://10.90.78.133:4450"
    volumes:
      - volume_domain_fe:/app/data
    networks:
      - app-network-domain-fe1

# **************** Volume ****************
volumes:
  volume_domain_fe:
    driver: local
    driver_opts:
      type: none
      o: 'bind'
      device: '/mnt/marzi/projects/scammagnifier/volumes'


# **************** Network ****************
networks:
  app-network-domain-fe1:
    driver: bridge

